### ISSUE TITLE
[Feature Request] Integrate the milkdrop visualizer

### ISSUE THREAD

**Issue by rajsite** [vitling/acid-banger#2]
The [butterchurn](https://github.com/jberg/butterchurn) library can be used to add support for Milkdrop visualizations by connecting up to AudioNodes.

![image](https://user-images.githubusercontent.com/1588923/115430229-cb863200-a1c9-11eb-944f-91ee0683b1ef.png)

**Comment by vitling** [comment]
This could indeed be a cool feature to have integrated, but it's definitely out of my intended scope for this project. I've added a note to the README about intended use that should explain why I'm not accepting feature requests for this project itself; but I will gladly share any cool derivative works that come about as a result of it :-)
