### ISSUE TITLE
CC is not recommended for software

### ISSUE THREAD

**Issue by thecjharries** [vitling/acid-banger#3]
CC licenses are great for most mediums. [Software is a different story](https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software).
> We recommend against using Creative Commons licenses for software. Instead, we strongly encourage you to use one of the very good software licenses which are already available.

Depending on how careful you'd like to be (and protective of the open source nature of this tool), something like [Apache 2.0](https://opensource.org/licenses/Apache-2.0) (requires only attribution; can be used in closed source) or [GPL 3](https://opensource.org/licenses/GPL-3.0) (requires attribution; cannot be used in closed source) would be better for the code in the repo. Typically FOSS projects apply some sort of FOSS license to their code and a CC license to the documentation and assets.

Really enjoy the project! Thanks so much for sharing

**Comment by vitling** [comment]
The thing is I don't really see it is software. This is an artistic creation, not a tool or a program for "use", and I would like people to treat it as such.
