### ISSUE TITLE
Volca / Pocket Operator sync output

### ISSUE THREAD

**Issue by brandond** [vitling/acid-banger#4]
I'd love to sync my Pocket Operators with the Acid Banger. They use some sort of click track on the left channel, same as the Korg Volca line I believe. Would it be possible to add an option to output this? Bonus points for using the audio recording APIs to take sync input.

**Comment by nagytech** [comment]
I've never owned a PO, but I've read up on how the sync cables can be used - seems to be 2 PPQN on the left channel.  Have you ever tried using the PO with VCV Rack?

I'm just working on the MIDI clock for this at the moment, so I'll tag you if I figure something out.

**Comment by vitling** [comment]
This sounds really cool, and i strongly encourage you to fork the project to make it possible! I've added a note to the README about intended use that should explain why I'm not accepting feature requests for this project itself; but I will gladly share any cool derivative works that come about as a result of it :-)

**Comment by brandond** [comment]
Will you accept PRs?

**Comment by adrianmancuso** [comment]
I think it would be cooler to fork it - this project is nicely refined and simple.

**Comment by nagytech** [comment]
@brandond 

I've added what I think will work for Pocket Operator integration on my fork: https://github.com/nagytech/acid-banger/tree/feat/pocket-operator

Since the author here isn't open to collaboration, I've opened an issue for you on my repo and we can continue the conversation there.
