### ISSUE TITLE
Custom sounds, e.g. drums.

### ISSUE THREAD

**Issue by soundshader** [vitling/acid-banger#76]

**Comment by vitling** [comment]
From the readme:

> This is an art project, not a software tool for music creation. I consider it to be finished, and as such I will likely not be accepting feature requests or feature-driven PRs. Please feel encouraged to fork the project and do something else with it if you would like - I love to see further creative work built on top of it.

Although if you just want to replace the drum sounds you can literally just drop different mp3s in the place of the files - no coding required
