### ISSUE TITLE
Please the UI more attractive

### ISSUE THREAD

**Issue by KTM-hacker** [vitling/acid-banger#8]

**Comment by nagytech** [comment]
See, (README.md)[https://github.com/vitling/acid-banger/blob/main/README.md]

> This is an art project, not a software tool for music creation. I consider it to be finished, and as such I will likely not be accepting feature requests or feature-driven PRs. Please feel encouraged to fork the project and do something else with it if you would like - I love to see further creative work built on top of it.

**Comment by vitling** [comment]
I spent many hours on the UI and I think it's beautiful.
You are, of course, free to fork this project and build your own UI to it.
